
# conda env create -f environment.yml
# conda activate UTBP_environment
# pip install -r requirements.txt

name: UTBP_environment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
